jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        submodules: true
    - continue-on-error: true
      name: Set up JDK 18.0.1
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 18.0.1
    - continue-on-error: true
      name: Show Build Versions
      run: ./gradlew -v
    - continue-on-error: true
      name: Build with Gradle
      run: ./gradlew jpackage
    - continue-on-error: true
      if: ${{ runner.os == 'Windows' || runner.os == 'macOS' }}
      name: Package zip distribution
      run: ./gradlew packageZipDistribution
    - continue-on-error: true
      if: ${{ runner.os == 'Linux' }}
      name: Package tar distribution
      run: ./gradlew packageTarDistribution
    - continue-on-error: true
      name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Sparrow Build - ${{ runner.os }}
        path: 'build/jpackage/*

          !build/jpackage/Sparrow/

          '
    - continue-on-error: true
      if: ${{ runner.os == 'Linux' }}
      name: Headless build with Gradle
      run: ./gradlew -Djava.awt.headless=true clean jpackage
    - continue-on-error: true
      if: ${{ runner.os == 'Linux' }}
      name: Package headless tar distribution
      run: ./gradlew -Djava.awt.headless=true packageTarDistribution
    - continue-on-error: true
      if: ${{ runner.os == 'Linux' }}
      name: Rename Headless Artifacts
      run: for f in build/jpackage/sparrow*; do mv -v "$f" "${f/sparrow/sparrow-server}";
        done;
    - continue-on-error: true
      if: ${{ runner.os == 'Linux' }}
      name: Upload Headless Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Sparrow Build - ${{ runner.os }} Headless
        path: 'build/jpackage/*

          !build/jpackage/Sparrow/'
    strategy:
      matrix:
        os:
        - windows-2022
        - ubuntu-20.04
        - macos-12
name: Package
on:
  repository_dispatch:
    types: trigger-ga___package.yaml
permissions:
  contents: read
